---
- hosts: lxadm01
  tasks:
    - lineinfile:
       path: /etc/ssh/sshd_config
       regexp: '^PermitRootLogin'
       line: PermitRootLogin yes
      notify:
        - Restart sshd

  handlers:
    - name: Restart sshd
      service: name=sshd state=restarted
