---
- hosts: all
  tasks:
  - name: Ansible Insert multiple lines using blockinfile
    blockinfile:
      dest: /tmp/block_output.txt
      block: |
        These lines are added by blockinfile module
        Check out the marker lines
      backup: yes
