---

- name: Network Getting Started First Playbook
  hosts: all
  tasks:
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_version }}"
